import type { Product } from './types'

export const PHONE_E164 = '33619871005'

/** Précommande trompe l'oeil : à récupérer sous 3 j après préco. Dispo gérée par Firebase (jours + stock). */
const TROMPE_LOEIL_PREORDER = { availableFrom: '2026-02-13', daysToPickup: 3 }

export const PRODUCTS: Product[] = [
    // Trompe l'oeil — Best sellers, bientôt disponibles, précommande à partir du 14/02/2026
    {
        id: 'trompe-loeil-mangue',
        name: "Trompe l'oeil Mangue",
        description: 'Morceaux de mangue fraîche, coulis de mangue, ganache mangue, pâte à sucre. Une création qui trompe l\'œil et régale les papilles.',
        price: 4,
        category: "Trompe l'oeil",
        image: '/Trompe-loeil-mangue.png',
        badges: ['best-seller'],
        preorder: TROMPE_LOEIL_PREORDER,
    },
    {
        id: 'trompe-loeil-citron',
        name: "Trompe l'oeil Citron",
        description: 'Zestes et jus de citron, crème au citron, ganache citron, pâte à sucre. Acidulé et frais, un trompe-l\'œil vitaminé.',
        price: 4,
        category: "Trompe l'oeil",
        image: '/trompe-loeil-citron.png',
        badges: ['best-seller'],
        preorder: TROMPE_LOEIL_PREORDER,
    },
    {
        id: 'trompe-loeil-pistache',
        name: "Trompe l'oeil Pistache",
        description: 'Pâte de pistache, crème pistache, ganache pistache, éclats de pistache, pâte à sucre. Onctueux et gourmand.',
        price: 4,
        category: "Trompe l'oeil",
        image: '/trompe-loeil-pistache.png',
        badges: ['best-seller'],
        preorder: TROMPE_LOEIL_PREORDER,
    },
    {
        id: 'trompe-loeil-passion',
        name: "Trompe l'oeil Passion",
        description: 'Fruit de la passion, coulis passion, crème passion, ganache passion, pâte à sucre. Exotique et intense.',
        price: 4,
        category: "Trompe l'oeil",
        badges: ['best-seller'],
        preorder: TROMPE_LOEIL_PREORDER,
    },
    {
        id: 'trompe-loeil-framboise',
        name: "Trompe l'oeil Framboise",
        description: 'Framboises fraîches, coulis de framboise, crème framboise, ganache framboise, pâte à sucre. Fruité et délicat.',
        price: 4,
        category: "Trompe l'oeil",
        image: '/trompe-loeil-framboise.PNG',
        badges: ['best-seller'],
        preorder: TROMPE_LOEIL_PREORDER,
    },
    {
        id: 'trompe-loeil-cacahuete',
        name: "Trompe l'oeil Cacahuète",
        description: 'Cacahuètes caramélisées, praliné cacahuète, ganache cacahuète, crème au beurre de cacahuète, pâte à sucre. Croquant et gourmand.',
        price: 4,
        category: "Trompe l'oeil",
        badges: ['best-seller'],
        preorder: TROMPE_LOEIL_PREORDER,
    },

    // Mini gourmandises (avec coulis au choix : Nutella, Crème Bueno, Spéculoos, Pistache)
    {
        id: 'mini-box-brownies',
        name: 'Box Mini Brownies',
        description: 'Mini brownies fondants avec coulis au choix (Nutella, Bueno, Spéculoos, Pistache).',
        price: 4.5,
        category: 'Mini Gourmandises',
        image: '/box-brownies.webp',
        sizes: [
            { label: 'Petite (≈200g)', ml: 200, price: 4.5 },
            { label: 'Grande (≈400g)', ml: 400, price: 8.5 },
        ],
    },
    {
        id: 'mini-box-cookies',
        name: 'Box Mini Cookies',
        description: 'Mini cookies croustillants avec coulis au choix (Nutella, Bueno, Spéculoos, Pistache).',
        price: 4,
        category: 'Mini Gourmandises',
        image: '/box-cookie.webp',
        sizes: [
            { label: 'Petite (≈180g)', ml: 180, price: 4 },
            { label: 'Grande (≈350g)', ml: 350, price: 7 },
        ],
    },
    {
        id: 'mini-box-pancakes',
        name: 'Box Mini Pancakes',
        description: 'Mini pancakes moelleux avec coulis au choix (Nutella, Bueno, Spéculoos, Pistache).',
        price: 4.5,
        category: 'Mini Gourmandises',
        image: '/box-pancakes.webp',
        sizes: [
            { label: 'Petite (≈200g)', ml: 200, price: 4.5 },
            { label: 'Grande (≈400g)', ml: 400, price: 8 },
        ],
    },
    {
        id: 'mini-box-mixte',
        name: 'LA MINI BOX MIXTE',
        description: 'Mini brownies + mini cookies + mini pancakes, coulis au choix.',
        price: 13,
        category: 'Boxes',
        image: '/La-mini-box-mixte.webp',
        badges: ['best-seller'],
        sizes: [
            { label: 'Box mixte S (~300g)', ml: 300, price: 13 },
            { label: 'Box mixte L (~600g)', ml: 600, price: 24 },
        ],
    },

    // Brownies
    {
        id: 'brownie-pistache-framboise',
        name: 'Pistache Framboise',
        description: 'Brownie fondant à la pistache, relevé par la fraîcheur de la framboise.',
        price: 3.5,
        category: 'Brownies',
        image: '/brownie-pistache-framboise.webp',
        badges: ['coup-de-coeur'],
    },
    {
        id: 'brownie-speculoos-framboise',
        name: 'Spéculoos Framboise',
        description: 'Fondant chocolaté, douceur épicée du spéculoos et touche fruitée.',
        price: 3.5,
        category: 'Brownies',
        image: '/brownie-speculoos-framboise.webp',
    },
    {
        id: 'brownie-fraise-vanille',
        name: 'Fraise Vanille',
        description: 'Brownie moelleux aux notes douces de vanille et de fraise.',
        price: 3.5,
        category: 'Brownies',
        image: '/brownie-fraise-vanille.webp',
    },
    {
        id: 'brownie-caramel-cacahuete',
        name: 'Caramel Cacahuète',
        description: 'Caramel fondant et cacahuète croquante sur une base chocolatée.',
        price: 3.5,
        category: 'Brownies',
        image: '/brownie-caramel-cacahuete.webp',
    },
    {
        id: 'brownie-el-mordjen-kinder',
        name: 'El Mordjen Kinder',
        description: 'Ultra gourmand, cœur fondant et éclats de Kinder Bueno.',
        price: 3.5,
        category: 'Brownies',
        image: '/brownie-elmordjene-kinder.webp',
        badges: ['populaire'],
    },
    {
        id: 'brownie-nutella-oreo',
        name: 'Nutella Oreo',
        description: 'Chocolat intense, Nutella fondant et croquant d\'Oreo.',
        price: 3.5,
        category: 'Brownies',
        image: '/brownie-nutella-oreo.webp',
        badges: ['best-seller'],
    },
    {
        id: 'brownie-patissiere-pecan',
        name: 'Pâtissière Pécan',
        description: 'Brownie crémeux à la crème pâtissière et pécan croquante.',
        price: 4,
        category: 'Brownies',
        image: '/brownie-patissiere-pecan.webp',
    },
    {
        id: 'brownie-tiramisu-cafe',
        name: 'Tiramisu Café',
        description: 'Inspiré du tiramisu, aux délicates notes de café.',
        price: 4,
        category: 'Brownies',
        image: '/brownie-tiramisu-cafe.webp',
    },
    {
        id: 'brownie-creme-brule-vanille',
        name: 'Crème Brûlé Vanille',
        description: 'Crémeux vanille avec une légère touche caramélisée.',
        price: 4,
        category: 'Brownies',
        image: '/brownie-creme-bruler.webp',
    },

    // Cookies
    {
        id: 'cookie-nutella-kinder-bueno',
        name: 'Nutella Kinder Bueno',
        description: 'Cœur fondant au Nutella sublimé par le croquant du Kinder Bueno.',
        price: 3,
        category: 'Cookies',
        image: '/cookie-kinder-bueno.webp',
        badges: ['best-seller'],
    },
    {
        id: 'cookie-nutella-oreo',
        name: 'Nutella Oreo',
        description: 'Intensément gourmand, entre chocolat fondant et éclats d\'Oreo.',
        price: 3,
        category: 'Cookies',
        image: '/Cookie-nutella-oreo.webp',
        badges: ['populaire'],
    },
    {
        id: 'cookie-speculoos-framboise',
        name: 'Spéculoos Framboise',
        description: 'Douceur épicée du spéculoos relevée par une framboise acidulée.',
        price: 3,
        category: 'Cookies',
        image: '/cookie-speculos-framboise.webp',
    },
    {
        id: 'cookie-nutella-fraise',
        name: 'Nutella Fraise',
        description: 'L\'alliance parfaite du chocolat fondant et de la fraîcheur de la fraise.',
        price: 3,
        category: 'Cookies',
        image: '/cookie-nutella-fraise.webp',
    },
    {
        id: 'cookie-fruits-rouges-bois',
        name: 'Fruits Rouges des Bois',
        description: 'Fondant et fruité, relevé par un coulis de fruits rouges.',
        price: 3,
        category: 'Cookies',
        image: '/cookie--fruit-rouges-des-bois.webp',
        badges: ['nouveau'],
    },
    {
        id: 'cookie-chocolat-blanc-framboise',
        name: 'Chocolat Blanc & Framboise',
        description: 'Douceur fondante du chocolat blanc réveillée par la framboise.',
        price: 3,
        category: 'Cookies',
        image: '/cookie-chocolat-blanc-framboise.webp',
    },
    {
        id: 'cookie-caramel-daim',
        name: 'Caramel Daim',
        description: 'Crème pâtissière onctueuse, éclats de Daim et caramel fondant.',
        price: 3,
        category: 'Cookies',
        image: '/cookie-caramel-daim.webp',
    },
    {
        id: 'cookie-caramel-cacahuete',
        name: 'Caramel Cacahuète',
        description: 'Crème pâtissière douce, caramel beurre salé et cacahuète croquante.',
        price: 3,
        category: 'Cookies',
        image: '/cookie-caramel-cacahuete.webp',
    },
    {
        id: 'cookie-pistache-framboise',
        name: 'Pistache Framboise',
        description: 'Subtil contraste entre pistache douce et framboise fruitée.',
        price: 3,
        category: 'Cookies',
        image: '/cookie-pistache-framboise.webp',
    },
    {
        id: 'cookie-praline-noix-pecan',
        name: 'Praliné Noix de Pécan',
        description: 'Crème pâtissière onctueuse et praliné aux éclats de noix de pécan.',
        price: 4,
        category: 'Cookies',
        image: '/cookie-praliné-noix-de-pecan.webp',
    },
    {
        id: 'cookie-tiramisu-cafe',
        name: 'Tiramisu Café',
        description: 'Inspiré du tiramisu, doux et délicatement café.',
        price: 4,
        category: 'Cookies',
        image: '/cookie-tiramisu-cafe.webp',
    },
    {
        id: 'cookie-creme-brulee-vanille',
        name: 'Crème Brûlée Vanille',
        description: 'Crémeux vanillé avec une touche caramélisée.',
        price: 4,
        category: 'Cookies',
        image: '/cookie-creme-bruler-vanille.webp',
    },

    // Layer cups
    {
        id: 'layer-fraise-vanille',
        name: 'Fraise Vanille',
        description: 'Douceur crémeuse aux saveurs de fraise et vanille.',
        price: 4,
        category: 'Layer Cups',
        image: '/layer-cup-fraise-vanille.webp',
        badges: ['coup-de-coeur'],
        sizes: [
            { label: '250 ml', ml: 250, price: 4 },
            { label: '360 ml', ml: 360, price: 6 },
            { label: '500 ml', ml: 500, price: 8 },
        ],
    },
    {
        id: 'layer-pistache-fraise',
        name: 'Pistache Fraise',
        description: 'Onctueux à la pistache relevé par la fraîcheur de la fraise.',
        price: 4,
        category: 'Layer Cups',
        image: '/layer-cup-pistache-fraise.webp',
        badges: ['coup-de-coeur'],
        sizes: [
            { label: '250 ml', ml: 250, price: 4 },
            { label: '360 ml', ml: 360, price: 6 },
            { label: '500 ml', ml: 500, price: 8 },
        ],
    },
    {
        id: 'layer-mangue-passion',
        name: 'Mangue Passion',
        description: 'Explosion tropicale de mangue et fruit de la passion.',
        price: 4,
        category: 'Layer Cups',
        image: '/layer-cup-mangue-passion.webp',
        badges: ['nouveau'],
        sizes: [
            { label: '250 ml', ml: 250, price: 4 },
            { label: '360 ml', ml: 360, price: 6 },
            { label: '500 ml', ml: 500, price: 8 },
        ],
    },
    {
        id: 'layer-lotus-speculoos',
        name: 'Lotus Spéculoos',
        description: 'Crème onctueuse aux notes épicées du spéculoos Lotus.',
        price: 4,
        category: 'Layer Cups',
        image: '/layer-cup-speculoos.webp',
        badges: ['populaire'],
        sizes: [
            { label: '250 ml', ml: 250, price: 4 },
            { label: '360 ml', ml: 360, price: 6 },
            { label: '500 ml', ml: 500, price: 8 },
        ],
    },
    {
        id: 'layer-framboise-speculoos',
        name: 'Framboise Spéculoos',
        description: 'Douceur du spéculoos relevée par l\'acidulé de la framboise.',
        price: 4,
        category: 'Layer Cups',
        image: '/layer-cup-framboise-speculoos.webp',
        sizes: [
            { label: '250 ml', ml: 250, price: 4 },
            { label: '360 ml', ml: 360, price: 6 },
            { label: '500 ml', ml: 500, price: 8 },
        ],
    },
    {
        id: 'layer-nutella-oreo',
        name: 'Nutella Oreo',
        description: 'Gourmandise chocolatée au Nutella et éclats d\'Oreo.',
        price: 4,
        category: 'Layer Cups',
        image: '/layer-cup-nutella-oreo.webp',
        badges: ['best-seller'],
        sizes: [
            { label: '250 ml', ml: 250, price: 4 },
            { label: '360 ml', ml: 360, price: 6 },
            { label: '500 ml', ml: 500, price: 8 },
        ],
    },

    // Boxes gourmandes
    {
        id: 'box-cookies',
        name: '🍪 Boxes Cookies',
        description: 'Assortiment de cookies au choix.',
        price: 15,
        category: 'Boxes',
        image: '/box-cookies.webp',
        sizes: [
            { label: 'Box de 6 cookies', ml: 6, price: 15 },
            { label: 'Box de 12 cookies', ml: 12, price: 35 },
        ],
    },
    {
        id: 'box-brownies',
        name: '🍫 Boxes Brownies',
        description: 'Assortiment de brownies au choix.',
        price: 18,
        category: 'Boxes',
        image: '/boxe-brownies.webp',
        sizes: [
            { label: 'Box de 6 brownies', ml: 6, price: 18 },
            { label: 'Box de 12 brownies', ml: 12, price: 38 },
        ],
    },
    {
        id: 'box-mixte',
        name: '🍪🍫 Boxes Mixtes',
        description: 'Un équilibre parfait entre cookies et brownies, parfums au choix.',
        price: 25,
        category: 'Boxes',
        image: '/box-mixte.webp',
        badges: ['coup-de-coeur', 'best-seller'],
        sizes: [
            { label: 'Box mixte 6 pièces (3 cookies + 3 brownies)', ml: 6, price: 25 },
            { label: 'Box mixte 12 pièces (6 cookies + 6 brownies)', ml: 12, price: 40 },
        ],
    },
    // Tiramisus personnalisés
    {
        id: 'tiramisu-personnalise',
        name: '🍰 TIRAMISUS PERSONNALISÉS',
        description: 'Crée ton tiramisu selon tes envies ✨',
        price: 3.5,
        category: 'Tiramisus',
        image: '/Tiramisu.webp',
        badges: ['best-seller', 'populaire'],
        sizes: [
            { label: 'Petit format', ml: 1, price: 3.5 },
            { label: 'Grand format', ml: 2, price: 6 },
        ],
    },
]
